### ISSUE TITLE
pegjs dependency not declared

### ISSUE THREAD

**Issue by cabo** [hildjj/quence#3]
When installing quence from scratch, the installation complains about a missing pegjs

```
npm ERR! Tell the author that this fails on your system:
npm ERR!     pegjs lib/grammar.pegjs
```

After installing pegjs, things work.

**Comment by hildjj** [comment]
It is declared in devDependencies.  You should only need pegjs if you modify grammar.pegjs, since I included the output, grammar.js.  What were the sequence of events that brought you to this error?  All I can think of is that "prepublish" calls pegjs, but that should only matter if you're doing "npm publish", where you should have done a developer install.

**Comment by cabo** [comment]
```
$ npm install -g quence

> quence@0.2.1 prepublish /Users/cabo/reo/new-big/quence
> pegjs lib/grammar.pegjs

sh: pegjs: command not found
```

Now the user error was that I did this in a directory that happened to have a clone from the repo called quence -- apparently it was trying to install that.  Wasn't aware of that trap, will be more careful next time.
